//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GunBak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kategori
    {
        public int kategoriId { get; set; }
        public string kategoriAd { get; set; }
        public string kategoriBaslik { get; set; }
    }
}
